### ISSUE TITLE
Please define external collaborators in code

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/hmpps-steel-thread#54]
Hi there

We now have a process to manage github collaborators in code:
https://github.com/ministryofjustice/github-collaborators/blob/main/README.md#github-external-collaborators

Please follow the procedure described there to grant @elainemartel access to this repository.

If you have any questions, please post in #ask-operations-engineering on Slack.

**Comment by kelliedesigner** [comment]
@Floppy @benilovj I believe this issue has been resolved another way, can you confirm and if so close this issue?

**Comment by benilovj** [comment]
Yep this is now solved.
